add dependents in docker-auto-builds

diff --git a/.github/workflows/docker-auto-build.yml b/.github/workflows/docker-auto-build.yml
--- a/.github/workflows/docker-auto-build.yml
+++ b/.github/workflows/docker-auto-build.yml
@@ -22,8 +22,8 @@ jobs:
           'ssh, push-latest',
           'xrootd, push-latest',
           'xrootd-noauth, push-latest',
-          'fs, prepend-rucio, prepend-release, push-tagged, push-latest'
-          ]
+          'fs, rucio-clients:release-#TAG, prepend-rucio, prepend-release, push-tagged, push-latest'
+        ]
       fail-fast: false
     
     steps:      
@@ -35,7 +35,7 @@ jobs:
       - name: Fetch all branches
         shell: bash
         run: |
-          REPO_URL=$(echo 'git://github.com/${{ github.repository_owner }}/containers.git') 
+          REPO_URL=$(echo 'https://github.com/${{ github.repository_owner }}/containers.git') 
           BRANCHES=$(git ls-remote --heads $REPO_URL | awk -F '\t' '{print $NF}' | cut -f3- -d'/')
           git fetch origin $BRANCHES
       
@@ -43,16 +43,28 @@ jobs:
         id: release_tag
         run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
       
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
+
+      - name: Login to DockerHub
+        uses: docker/login-action@v1 
+        with:
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+      
       - name: Generate Docker Image Names
         id: release
         shell: bash
         run: |
           # Generates the image tags for the containers present in the containers repository
           # The input is inn CSV format:
-          # {sub_directory}, {config_paramms}
+          # {sub_directory}, {parent_image}, {config_paramms}
           # where,
           #     sub_directory: name of the sub_directory in rucio/containers reposistory that contains
           #                    the Dockerfile
+          #     parent_image:  OPTIONAL name of the parent image that is required to be available on Docker Hub before building this image.
+          #                    Parent images must begin with rucio- and can specify the #TAG placeholder to refer to the current tag being pushed.
+          #                    For example, rucio-clients:release-#TAG
           #     config_params: These are described in the CONFIG section and are used to generate 
           #                    the image tags that will be pushed to DockerHub fot the given {sub_directory}
           #
@@ -78,9 +90,11 @@ jobs:
 
           CONTEXT=$(echo "${{ matrix.context }}")
           CONTEXT_DIR=$(echo "${{ matrix.context }}" | cut -d, -f1 )
+          PARENT=$(echo "${{ matrix.context }}" | cut -d, -f2 | xargs)
           GIT_TAG=${{ steps.release_tag.outputs.version }}
           BASE_TAG="${{ github.repository_owner}}/"
-          
+          PARENT_IMAGE_AVAILIBILITY_INTERVAL=60
+          MAX_ATTEMPTS=10
           GIT_TAG_COMMIT_SHA=$(echo $(git rev-list -n 1 $GIT_TAG))
           GIT_MASTER_LATEST_COMMIT_SHA=$(echo $(git ls-remote --heads origin | grep master  |  awk -F '\t' '{print $1}'))
 
@@ -135,22 +149,34 @@ jobs:
             TAGS_TO_PUSH="$BASE_TAG:latest"
           fi
 
+          if [[ $PARENT == rucio-* ]]; then 
+            if [[ ${PARENT} =~ .*"#TAG".* ]]; then
+            PARENT=${PARENT/\#TAG/$GIT_TAG}
+            fi
+
+            PARENT="${{ github.repository_owner }}/${PARENT}"
+            for i in $(seq 1 1 $MAX_ATTEMPTS)
+            do
+                echo "Attempt ${i}: Waiting for $PARENT to be available on Docker Hub"
+                docker pull $PARENT > /dev/null && echo "$PARENT found" && break || echo "Parent not found! Waiting $PARENT_IMAGE_AVAILIBILITY_INTERVAL seconds"
+                sleep $PARENT_IMAGE_AVAILIBILITY_INTERVAL
+
+                if [[ $i == $MAX_ATTEMPTS ]]; then
+                    echo "$PARENT image is not available on Docker Hub. Dependent images will not be pushed."
+                    exit 1
+                fi
+            done
+          else
+            echo "No parent image has been specified for $CONTEXT_DIR. Parent images are the second parameter in the csv build description and must begin with '/rucio-'."
+          fi
+  
+
           echo ::set-output name=git_tag::$GIT_TAG
           echo ::set-output name=tags::$TAGS_TO_PUSH
           echo ::set-output name=context_dir::$CONTEXT_DIR
+          
 
           echo "For tag: $GIT_TAG, the following images will be pushed: $TAGS_TO_PUSH"
-          
-      - name: Set up Docker Buildx
-        if: steps.release.outputs.tags != ''
-        uses: docker/setup-buildx-action@v1
-
-      - name: Login to DockerHub
-        if: steps.release.outputs.tags != ''
-        uses: docker/login-action@v1 
-        with:
-          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
 
       - name: Build and push
         if: steps.release.outputs.tags != ''
@@ -161,3 +187,4 @@ jobs:
           push: true
           tags: '${{ steps.release.outputs.tags }}'
           build-args: TAG=${{ steps.release.outputs.git_tag }}
+  
